// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvfm00TGKTLvguakEFAnhAw2NplSFB0I',
    appId: '1:403486739048:web:e96ec956fca5c670c349dd',
    messagingSenderId: '403486739048',
    projectId: 'cinema-ticket-booking-ap-42dc4',
    authDomain: 'cinema-ticket-booking-ap-42dc4.firebaseapp.com',
    storageBucket: 'cinema-ticket-booking-ap-42dc4.firebasestorage.app',
    measurementId: 'G-C75VV07KMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt-r61l34wjHChGopthgXFrfBC6jF4iI0',
    appId: '1:403486739048:android:997656ead8d86c6ec349dd',
    messagingSenderId: '403486739048',
    projectId: 'cinema-ticket-booking-ap-42dc4',
    storageBucket: 'cinema-ticket-booking-ap-42dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4yWP070gVqzM5Htmcxnr2D0iVYNBjAY',
    appId: '1:403486739048:ios:4ca149e8fb19159dc349dd',
    messagingSenderId: '403486739048',
    projectId: 'cinema-ticket-booking-ap-42dc4',
    storageBucket: 'cinema-ticket-booking-ap-42dc4.firebasestorage.app',
    iosClientId: '403486739048-09loatoc4nefphbdk799dd5ncui8opun.apps.googleusercontent.com',
    iosBundleId: 'com.example.middleExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM4yWP070gVqzM5Htmcxnr2D0iVYNBjAY',
    appId: '1:403486739048:ios:4ca149e8fb19159dc349dd',
    messagingSenderId: '403486739048',
    projectId: 'cinema-ticket-booking-ap-42dc4',
    storageBucket: 'cinema-ticket-booking-ap-42dc4.firebasestorage.app',
    iosClientId: '403486739048-09loatoc4nefphbdk799dd5ncui8opun.apps.googleusercontent.com',
    iosBundleId: 'com.example.middleExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbvfm00TGKTLvguakEFAnhAw2NplSFB0I',
    appId: '1:403486739048:web:dbff74780855d5cac349dd',
    messagingSenderId: '403486739048',
    projectId: 'cinema-ticket-booking-ap-42dc4',
    authDomain: 'cinema-ticket-booking-ap-42dc4.firebaseapp.com',
    storageBucket: 'cinema-ticket-booking-ap-42dc4.firebasestorage.app',
    measurementId: 'G-W9EZ2CB3PP',
  );
}
